# Use Eclipse Temurin JDK 17
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Copy built jar (mvn package will produce target/*.jar)
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]
