auth-service:
  build: ./auth-service
  ports:
    - "8081:8080"
  environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ecommerce
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=postgres
    - JWT_SECRET=ChangeThisSecret
  depends_on:
    - postgres
